management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          group: messages.group
          binder: local_rabbit
        output:
          destination: queue.log.messages
          group: messages.group
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /